### PR TITLE
Current Status. Have to check it

### PR DESCRIPTION
**Pull request by DTobii**
Please review both files with the sources we get at moodle (mail)!

### CODE REVIEW

**Review by kai-oswald — CHANGES_REQUESTED** [review]
associations in class diagram (1:1, 1:n, m:n)

**Comment by DTobii** [comment]
Added additional classdiagramm. What do you say? Something missing? URL Okay?

**Review by kai-oswald — DISMISSED** [review]

**Comment by Hurba** [comment]
I would change the layout of the assossiations. Put the number next to the belonging box. By doing this you can delete the name near the number.
In addition i would seperate the lines between model or routes and the controller.

**Comment by kai-oswald** [comment]
I agree with @Hurba. But by definition we need to use an assoication name. Maybe use some better names than "kennt".

**Comment by mlechler** [comment]
I agree with @Hurba and @kai-oswald 

But @DTobii, why the hell don't you use the naming-convention for new branches.

**Comment by TrAnn3l** [comment]
I agree with @Hurba and @kai-oswald 
Especially i agree with @mlechler, @DTobii use the naming-convention!

**Comment by DTobii** [comment]
Then make a proposal for better names  @kai-oswald

**Comment by kai-oswald** [comment]
clockwise: 
- Konfiguration / Standardeinstellungen
- Konfiguration / Standardeinstellungen
- Zuweisung
- Verwendung/Manipulation von ..
- Kommunikation

If we need to use english names, please use the corresponding translations.

**Review by kai-oswald — CHANGES_REQUESTED** [review]
rename association names

**Review by kai-oswald — APPROVED** [review]

**Pull request merged**
