### PR TITLE
Issue 14 system url lennart

### PR DESCRIPTION
**Pull request by TrAnn3l**
Many fixes regarding shortening URLs.
Something is causing a redirect-loop, needs more investigation but the app still works.

### CODE REVIEW

**Comment by DTobii** [comment]
When happens redirect-loop?

**Comment by kai-oswald** [comment]
Redirect-loop happens on every request?

**Comment by TrAnn3l** [comment]
Yes, it tries to get /undefined but gets redirected to /undefined

**Comment by DTobii** [comment]
Routes okay?

**Comment by TrAnn3l** [comment]
Yes

**Pull request merged**
